### ISSUE TITLE
error loading Web UI

### ISSUE THREAD

**Issue by YnievesDotNet** [diladele/websafety-issues#166]
I try use the diladele webfilter, but i can start the service, I follow the official doc of 4.9, but dont work, when i browse the http://proxy.lan show error.

here the log

https://gist.github.com/YnievesDotNet/1644c4521cd478b7b63e89b08cbb2563

Thanks Yoinier.

**Comment by ra-at-diladele-com** [comment]
May it be you are using it on desktop version of CentOS/Fedora?

**Comment by YnievesDotNet** [comment]
I have using centos 7, without desktop package

**Comment by YnievesDotNet** [comment]
what data of my server you need?

**Comment by ra-at-diladele-com** [comment]
I would first do the "yum update", then reboot server. The problems seems to be due to some update of the core python modules - see http://stackoverflow.com/questions/41829550/how-to-fix-pip-being-proken-after-installing-line-profiler

**Comment by YnievesDotNet** [comment]
[root@proxy ~]# yum update
Complementos cargados:fastestmirror
Loading mirror speeds from cached hostfile
No packages marked for update


rebooting now

**Comment by YnievesDotNet** [comment]
the error continue after reboot

thanks

**Comment by YnievesDotNet** [comment]
I comment the line commended, and now work fine, thanks.

Ynieves
