### ISSUE TITLE
Upgrade docker container to 5.2

### ISSUE THREAD

**Issue by henry-nicolas** [diladele/websafety-issues#457]
The container diladele/websafety still provide only 4.9.

Please upgrade it to 5.2 so the Docker user also benefits from the latest features available.

Regards,

**Comment by ra-at-diladele-com** [comment]
Planned now

**Comment by ra-at-diladele-com** [comment]
Ok everything updated at https://github.com/diladele/docker-websafety - need to push image to docker hub

**Comment by ra-at-diladele-com** [comment]
Done, works and tested on Mac (Docker). Works as expected.
