### ISSUE TITLE
Reports: No table headers and strange link on the YouTube report

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#46]
If user clicks on title of the video it should be opened in another browser window - on youtube site.
Currently we have some strange text on the right. See attached image
![yt](https://cloud.githubusercontent.com/assets/2544598/22878150/ea2088be-f1d8-11e6-8465-ba1216979762.png)

**Comment by ea-at-diladele-com** [comment]
need testing

**Comment by ra-at-diladele-com** [comment]
ok link is fixed; the headers not - but I will make another bug for it
