### ISSUE TITLE
Documentation update for config sync service firewall rules

### ISSUE THREAD

**Issue by johannrichard** [diladele/websafety-issues#471]
The configuration [documentation for firewall rules](https://docs.diladele.com/tutorials/transparent_proxy_ubuntu/final.html?highlight=iptables)  does not include the rules necessary for the sync server and client. As far as I could determine, the minimum needed for the server would be something similar to the following (assuming ens160 is the concerned network interface used for the service/client): 

```
-A INPUT -i ens160 -p tcp --dport 18999 -j ACCEPT
-A INPUT -i ens160 -p tcp --dport 18889 -j ACCEPT
```

**Comment by ra-at-diladele-com** [comment]
Added at the bottom of https://docs.diladele.com/administrator_guide_6_0/active_directory_extra/redundancy/cluster.html
