### ISSUE TITLE
Traffic: wsicapd now writes "user_eui" (MAC address) to *.monitor 

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#5]
We must be able to see it in wsmgrd (at least see in Surfing Now?). 

This is very useful when we use Pseudo Auth. We enable Pseudo Auth and Squid starts to give us the MAC address of the remote device. We then take this MAC address from Surfing Now and add a label to it. Save and Restart and label is visible in Surfing Now too. Very handy for home deployment scenarios.

**Comment by ea-at-diladele-com** [comment]
user_eui is part of db both for runtime and monitoring. can be accessed also from the webui thru surfing_record.user_eui field.

please change the GUI.

**Comment by ra-at-diladele-com** [comment]
Done, seems to work correctly.
