### ISSUE TITLE
Squid activities log - if log format is not default - we dump error to log for each record in the db

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#501]
and thus HDD gets full.
We need to stop generating report after finding out that the logformat is not default and is not understandable for us.

**Comment by ra-at-diladele-com** [comment]
Added this customisation to the template file, /opt/websafety/var/console/squid/templates/squid/conf/logfile.conf.

```
logformat nswsmc %ts.%03tu|%{%Y/%m/%d %H:%M:%S}tl|%{%z}tl|%tr|%dt|%>a|%>A|%un|%Ss|%Sh|%03>Hs|%mt|%>st|%<st|%<sS|%rm|%{Host}>h|%<a|%ru|%{Refer$

access_log stdio:/var/log/squid/access.log nswsmc
```

**Comment by ea-at-diladele-com** [comment]
Need to test.

**Comment by ra-at-diladele-com** [comment]
Ok fix confirmed; we now print not more than 5 errors about not being able to parse the lines in the access log.
