### ISSUE TITLE
Make VM with Squid 4 as experimental build

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#696]
See #614. Everything is ready and working; just need to build for VA and announce to Early Adopters.

**Comment by WTFMaster** [comment]
What do you think about Tinyproxy? Very small footprint!

https://tinyproxy.github.io/

**Comment by ra-at-diladele-com** [comment]
Web Safety relies on Squid's ICAP interface to get access to proxied traffic, I am not sure if tinyproxy supports that.

**Comment by ra-at-diladele-com** [comment]
Done in https://github.com/diladele/websafety-virtual-appliance/tree/release-6.4.0/scripts.ubuntu18
