### ISSUE TITLE
User Labelling label stays "inactive" even if its activated

### ISSUE THREAD

**Issue by WTFMaster** [diladele/websafety-issues#697]
Version: Web Safety for Squid Proxy, version 6.2.0.4570-armhf-linux-debian9

![grafik](https://user-images.githubusercontent.com/25774289/37487403-bb468d2c-2891-11e8-814c-3e89db9cb3e3.png)

![grafik](https://user-images.githubusercontent.com/25774289/37487374-a80fc084-2891-11e8-88ce-7d031b6fab9f.png)

**Comment by ra-at-diladele-com** [comment]
Fixed in the new 6.2 build. To fix it, open the /opt/websafety/var/console/squid/views/auth.py and add at line 810 the following (be sure to use spaces to align with above line).

```
context['authlabel']    = AuthLabel.objects.first()
```
