### ISSUE TITLE
Adding "User Labelled"-Devices to Policies

### ISSUE THREAD

**Issue by WTFMaster** [diladele/websafety-issues#699]
Right now, I see no way to add Clients in my network which are authenticated by "User Labelling" (MAC-address) to particular Policies.

**Comment by ra-at-diladele-com** [comment]
Just checked and it seems to be working. What needs to be done:

- enable user labelling
- add label for static IP of device1  - say user1
- add add label for MAC of device 2, leave IP empty - say user2

Save and Restart. 

Now to UI / We Safety / Policy / Your Desired Policy. Choose Members / Member Name. Click Add and type *user1*, then add the *user2* in the same way. Click Save and Restart

Try to navigate from device1 - in Traffic Monitor this label (treated as user name) will be assigned the desired policy.

Try to navigate from device2 - in Traffic Monitor this label (treated as user name) will be assigned the desired policy.

Seems to be working.

NOTE: all other proxy authentication MUST be disabled. User labelling only works by its own.
Please close the issue if it is fine.
