### ISSUE TITLE
"User Labelled" Clients will not show up in Traffic Monitor

### ISSUE THREAD

**Issue by WTFMaster** [diladele/websafety-issues#701]
Clients which are authenticated by "User Labelling" are not shown in the Traffic Monitor. Only "named User" will show up.

**Comment by ra-at-diladele-com** [comment]
Not sure if I understood you correctly, may be related to #699. 
I have the following Surfing Now
![labelling](https://user-images.githubusercontent.com/2544598/37523698-05c91b80-2928-11e8-8c2f-ca4893efbd5e.png)

With the following labels
![labelling](https://user-images.githubusercontent.com/2544598/37523745-24c1ef76-2928-11e8-9491-c4672c983474.png)
