### ISSUE TITLE
Traffic Reporter: ability to anonymize user ip and user name in all channels

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#72]
Add "Anonymize Users" Check Box to Web UI and to wsmgrd.json - if it is set to true then the all user names and user ips arriving to traffic syncs MUST be changed to - (dash)

**Comment by ra-at-diladele-com** [comment]
the monitor.json now contains "history_anonymize_names": false.

If set to true, please replace user name and user ip arriving from wsicapd daemon to - (dash)
This is required for log anonymization for example in public filtering in Germany.

**Comment by ea-at-diladele-com** [comment]
need testing.

**Comment by ra-at-diladele-com** [comment]
works
