### ISSUE TITLE
Azure image - we need to hide network settings (IP address and such)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#773]
This does not make sense in Azure.

**Comment by Chrisnetika** [comment]
Dumb question,as an early adopter tester how are we suppose to test filtering features if it is disabled? *Scratchs head*

**Comment by ra-at-diladele-com** [comment]
It is built in with every early build - no need to do anything - install and just works. I will send you the license now.

**Comment by ra-at-diladele-com** [comment]
Sorry I need your e-mail? Please send it to support@diladele.com

**Comment by Chrisnetika** [comment]
Email sent

**Comment by ra-at-diladele-com** [comment]
The network settings are able to be hidden in Azure, but we need to adapt the scripts.

**Comment by ra-at-diladele-com** [comment]
For now this is not needed, as even in Azure admin might want to set the static IP
