### ISSUE TITLE
Traffic: wsicapd now writes "membership" to *.monitor 

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#9]
the membership value that triggered selection of policy is now written to GUID.monitor for each ICAP transaction. Need to add it to the database and make reporting with conditions on this value.

**Comment by ra-at-diladele-com** [comment]
please implement upload into monitoring database and reassign the bug to me to implement limitations in the Web UI. Then we need to implement these limits in reporting.

**Comment by ea-at-diladele-com** [comment]
I suppose you meant "member"? This requires quite some changes in the db. thorough testing needed.

**Comment by ra-at-diladele-com** [comment]
Good, now it is present in the Admin UI (Surfing Now and History) - but we also need to make reports for it - see #109.
